server:
  port: 33300
spring:
  application:
    name: YONYOU-GATEWAY-SERVICE
  mvc:
    favicon:
      enabled: true
eureka:
  instance:
  #instance-id: ${spring.application.name}:${server.port}
  prefer-ip-address: true                     # 设置微服务调用地址为IP优先（缺省为false）
  #lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
  #lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
#    healthcheck:
#      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/ # 指定服务注册中心的地址
zuul:
#  SendErrorFilter:
#    post:
#      disabled: true #自定义异常
  #设置忽略的服务，即配置后将不会被路由（但对于明确配置在路由中的，将不会被忽略）
  ignored-services: "*"
  sensitive-headers:
  routes:
#    HZ_LOGIN:
#      path: /member/**
#      url: http://cpc.ccb.com:33300/member/
#    HZ_SYSTEM:
#      path: /system/**
#      url: http://cpc.ccb.com:33300/system
#    HZ_WEBDOCS:
#      path: /webdocs/**
#      url: http://cpc.ccb.com:33300/webdocs
    #工作台路由
    YONYOU-WORKBENCH-WEB:
      path: /mall/**
      serviceId: YONYOU-WORKBENCH-WEB
#    cpu-cdn:
#      path: /cpu-cdn/**
#      serviceId: http://localhost:8550/static/cpu-cdn/
#    static:
#      path: /malldoc/**
#      serviceId: http://localhost:8550/static
    name1:
      path: /pages/**
      serviceId: http://localhost:8550/static/pages/
    mall-service:
      path: /yuncai/**
      serviceId: YONYOU-WORKBENCH-WEB
    file-service:
      path: /file/**
      serviceId: YONYOU-FILE-SERVICE
    #云采超市路由
    market:
      path: /market/**
      serviceId: YONYOU-MARKET-WEB
    market-service:
      path: /mall-basedoc/**
      serviceId: YONYOU-MARKET-WEB
    market-business-service:
      path: /mall-business/**
      serviceId: YONYOU-MARKET-WEB
    supplier-relationship-service:
          path: /supplier-relationship/**
          serviceId: YONYOU-SUPPLIER-RELATIONSHIP-GRAPH
    INTERFACE:
          path: /interface/**
          serviceId: YONYOU-INTERFACE-SERVICE
    GATEWAY:
          path: /gateway/**
          serviceId: YONYOU-INTERFACE-SERVICE

    max:
    host:
      connections: 500
      socket-timeout-millis: 600000
      connect-timeout-millis: 600000
  add-host-header: true #路由转发前为请求设置Host信息

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          stratehy: THREAD
          thread:
            timeoutInMilliseconds: 600000

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true


multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb
