server:
  port: 8560
  cloud:
    config:
      url: http://127.0.0.1:8888
      name: springCloudApp
      profile: ${config.profile:dev}
#service name
spring:
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
  application:
    name: YONYOU-MARKET-WEB
  freemarker:
    template-loader-path: /templates
  mvc:
    static-path-pattern: /public/**
  data:
    mongodb:
      uri: mongodb://39.104.87.29:27017/gpc
    elasticsearch:
      cluster-name: yonyou
      cluster-nodes: 39.104.87.29:9300
 # session:
 #   store-type: none
  redis:
    port: 33302
    host: 106.75.216.203
    password: ebs_stdv5_11
    pool:
      max-active: 100
      max-idle: 5
      max-wait: 600000
ccb:
  isTrans: uuuu
yyc:
  sysId: ccbtest1
ncbase:
  appid: ccb
  server: ccb
  checkin:
    uri: ccb
purchase:
  bill:
    checkout:
      url: ccb

secret_iv: b49e425a
secret_key: 69c5deecf03a8ddb2fd934f5@747/c#
sr_search_url: http://mall.ccb.com/v2/cpc/commodity/search
sr_url: http://pl4mall.ccb.com/ecp/view/cpc/buy/commodity/search