ccb:
    isTrans: uuuu
charset: ISO8859-1
connect_timeout: 10
defaultBucket: uappr
defaultBucketRead: uapread
fdfsread_server: 39.104.87.29
multipart:
    maxFileSize: 10Mb
    maxRequestSize: 50Mb
network_timeout: 30
server:
    port: 8580
spring:
    application:
        name: YONYOU-FILE-SERVICE
    cloud:
        config:
            name: ccb_config
            profile: ${config.profile:dev}
            uri: http://127.0.0.1:8888
storeType: FastDfs
tracker_server: 39.104.87.29:22122
